- hosts: all
  become: true
  tasks:
    - name: Check kubectl version
      command: kubectl version --client
      register: kubectl_version

    - name: Print kubectl version
      debug:
        msg: "Kubectl version: {{ kubectl_version.stdout }}"

    - name: Test kubectl command
      command: kubectl get nodesg
      register: kubectl_nodes

    - name: Print kubectl nodes output
      debug:
        msg: "Kubectl nodes output: {{ kubectl_nodes.stdout }}"
