kind: Deployment
apiVersion: apps/v1
metadata:
  name: myimage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myimage
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
      - name: myimage
        image: madhurshinde/my_docker_image
        imagePullPolicy: Always
        ports:
        - containerPort: 80
