kind: Service
apiVersion: v1
metadata:
  name: myimage
  labels:
    app: myimage
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: myimage
  type: LoadBalancer
